<?php

namespace InstitutionBundle\Repository;

/**
 * ReferentialCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferentialCityRepository extends \Doctrine\ORM\EntityRepository
{
}
