institution:
    resource: "@InstitutionBundle/Controller/"
    type:     annotation
    prefix:   /

crawler:
    resource: "@CrawlerBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /
